// source: Session.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.vip.qsos.im.lib.model.proto.Model', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.vip.qsos.im.lib.model.proto.Model = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.vip.qsos.im.lib.model.proto.Model, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.vip.qsos.im.lib.model.proto.Model.displayName = 'proto.vip.qsos.im.lib.model.proto.Model';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.vip.qsos.im.lib.model.proto.Model.prototype.toObject = function(opt_includeInstance) {
  return proto.vip.qsos.im.lib.model.proto.Model.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.vip.qsos.im.lib.model.proto.Model} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.vip.qsos.im.lib.model.proto.Model.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    account: jspb.Message.getFieldWithDefault(msg, 2, ""),
    nid: jspb.Message.getFieldWithDefault(msg, 3, ""),
    deviceid: jspb.Message.getFieldWithDefault(msg, 4, ""),
    host: jspb.Message.getFieldWithDefault(msg, 5, ""),
    channel: jspb.Message.getFieldWithDefault(msg, 6, ""),
    devicemodel: jspb.Message.getFieldWithDefault(msg, 7, ""),
    clientversion: jspb.Message.getFieldWithDefault(msg, 8, ""),
    systemversion: jspb.Message.getFieldWithDefault(msg, 9, ""),
    bindtime: jspb.Message.getFieldWithDefault(msg, 10, 0),
    longitude: jspb.Message.getFloatingPointFieldWithDefault(msg, 11, 0.0),
    latitude: jspb.Message.getFloatingPointFieldWithDefault(msg, 12, 0.0),
    location: jspb.Message.getFieldWithDefault(msg, 13, ""),
    apns: jspb.Message.getFieldWithDefault(msg, 14, 0),
    state: jspb.Message.getFieldWithDefault(msg, 15, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.vip.qsos.im.lib.model.proto.Model}
 */
proto.vip.qsos.im.lib.model.proto.Model.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.vip.qsos.im.lib.model.proto.Model;
  return proto.vip.qsos.im.lib.model.proto.Model.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.vip.qsos.im.lib.model.proto.Model} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.vip.qsos.im.lib.model.proto.Model}
 */
proto.vip.qsos.im.lib.model.proto.Model.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setAccount(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setNid(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setDeviceid(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setHost(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setChannel(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setDevicemodel(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setClientversion(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setSystemversion(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setBindtime(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setLongitude(value);
      break;
    case 12:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setLatitude(value);
      break;
    case 13:
      var value = /** @type {string} */ (reader.readString());
      msg.setLocation(value);
      break;
    case 14:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setApns(value);
      break;
    case 15:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setState(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.vip.qsos.im.lib.model.proto.Model.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.vip.qsos.im.lib.model.proto.Model.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.vip.qsos.im.lib.model.proto.Model} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.vip.qsos.im.lib.model.proto.Model.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getAccount();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getNid();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getDeviceid();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getHost();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getChannel();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getDevicemodel();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getClientversion();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getSystemversion();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getBindtime();
  if (f !== 0) {
    writer.writeInt64(
      10,
      f
    );
  }
  f = message.getLongitude();
  if (f !== 0.0) {
    writer.writeDouble(
      11,
      f
    );
  }
  f = message.getLatitude();
  if (f !== 0.0) {
    writer.writeDouble(
      12,
      f
    );
  }
  f = message.getLocation();
  if (f.length > 0) {
    writer.writeString(
      13,
      f
    );
  }
  f = message.getApns();
  if (f !== 0) {
    writer.writeInt32(
      14,
      f
    );
  }
  f = message.getState();
  if (f !== 0) {
    writer.writeInt32(
      15,
      f
    );
  }
};


/**
 * optional int64 id = 1;
 * @return {number}
 */
proto.vip.qsos.im.lib.model.proto.Model.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.vip.qsos.im.lib.model.proto.Model} returns this
 */
proto.vip.qsos.im.lib.model.proto.Model.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string account = 2;
 * @return {string}
 */
proto.vip.qsos.im.lib.model.proto.Model.prototype.getAccount = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.vip.qsos.im.lib.model.proto.Model} returns this
 */
proto.vip.qsos.im.lib.model.proto.Model.prototype.setAccount = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string nid = 3;
 * @return {string}
 */
proto.vip.qsos.im.lib.model.proto.Model.prototype.getNid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.vip.qsos.im.lib.model.proto.Model} returns this
 */
proto.vip.qsos.im.lib.model.proto.Model.prototype.setNid = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string deviceId = 4;
 * @return {string}
 */
proto.vip.qsos.im.lib.model.proto.Model.prototype.getDeviceid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.vip.qsos.im.lib.model.proto.Model} returns this
 */
proto.vip.qsos.im.lib.model.proto.Model.prototype.setDeviceid = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string host = 5;
 * @return {string}
 */
proto.vip.qsos.im.lib.model.proto.Model.prototype.getHost = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.vip.qsos.im.lib.model.proto.Model} returns this
 */
proto.vip.qsos.im.lib.model.proto.Model.prototype.setHost = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string channel = 6;
 * @return {string}
 */
proto.vip.qsos.im.lib.model.proto.Model.prototype.getChannel = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.vip.qsos.im.lib.model.proto.Model} returns this
 */
proto.vip.qsos.im.lib.model.proto.Model.prototype.setChannel = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string deviceModel = 7;
 * @return {string}
 */
proto.vip.qsos.im.lib.model.proto.Model.prototype.getDevicemodel = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.vip.qsos.im.lib.model.proto.Model} returns this
 */
proto.vip.qsos.im.lib.model.proto.Model.prototype.setDevicemodel = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string clientVersion = 8;
 * @return {string}
 */
proto.vip.qsos.im.lib.model.proto.Model.prototype.getClientversion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.vip.qsos.im.lib.model.proto.Model} returns this
 */
proto.vip.qsos.im.lib.model.proto.Model.prototype.setClientversion = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional string systemVersion = 9;
 * @return {string}
 */
proto.vip.qsos.im.lib.model.proto.Model.prototype.getSystemversion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.vip.qsos.im.lib.model.proto.Model} returns this
 */
proto.vip.qsos.im.lib.model.proto.Model.prototype.setSystemversion = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional int64 bindTime = 10;
 * @return {number}
 */
proto.vip.qsos.im.lib.model.proto.Model.prototype.getBindtime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {number} value
 * @return {!proto.vip.qsos.im.lib.model.proto.Model} returns this
 */
proto.vip.qsos.im.lib.model.proto.Model.prototype.setBindtime = function(value) {
  return jspb.Message.setProto3IntField(this, 10, value);
};


/**
 * optional double longitude = 11;
 * @return {number}
 */
proto.vip.qsos.im.lib.model.proto.Model.prototype.getLongitude = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 11, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.vip.qsos.im.lib.model.proto.Model} returns this
 */
proto.vip.qsos.im.lib.model.proto.Model.prototype.setLongitude = function(value) {
  return jspb.Message.setProto3FloatField(this, 11, value);
};


/**
 * optional double latitude = 12;
 * @return {number}
 */
proto.vip.qsos.im.lib.model.proto.Model.prototype.getLatitude = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 12, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.vip.qsos.im.lib.model.proto.Model} returns this
 */
proto.vip.qsos.im.lib.model.proto.Model.prototype.setLatitude = function(value) {
  return jspb.Message.setProto3FloatField(this, 12, value);
};


/**
 * optional string location = 13;
 * @return {string}
 */
proto.vip.qsos.im.lib.model.proto.Model.prototype.getLocation = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 13, ""));
};


/**
 * @param {string} value
 * @return {!proto.vip.qsos.im.lib.model.proto.Model} returns this
 */
proto.vip.qsos.im.lib.model.proto.Model.prototype.setLocation = function(value) {
  return jspb.Message.setProto3StringField(this, 13, value);
};


/**
 * optional int32 apns = 14;
 * @return {number}
 */
proto.vip.qsos.im.lib.model.proto.Model.prototype.getApns = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 14, 0));
};


/**
 * @param {number} value
 * @return {!proto.vip.qsos.im.lib.model.proto.Model} returns this
 */
proto.vip.qsos.im.lib.model.proto.Model.prototype.setApns = function(value) {
  return jspb.Message.setProto3IntField(this, 14, value);
};


/**
 * optional int32 state = 15;
 * @return {number}
 */
proto.vip.qsos.im.lib.model.proto.Model.prototype.getState = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 15, 0));
};


/**
 * @param {number} value
 * @return {!proto.vip.qsos.im.lib.model.proto.Model} returns this
 */
proto.vip.qsos.im.lib.model.proto.Model.prototype.setState = function(value) {
  return jspb.Message.setProto3IntField(this, 15, value);
};


goog.object.extend(exports, proto.vip.qsos.im.lib.model.proto);
