// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

package vip.qsos.im.lib.model.proto;

public final class MessageProto {
  private MessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface ModelOrBuilder extends
      // @@protoc_insertion_point(interface_extends:vip.qsos.im.lib.model.proto.Model)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * 消息ID
     * </pre>
     *
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    long getId();

    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>string action = 2;</code>
     * @return The action.
     */
    java.lang.String getAction();
    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>string action = 2;</code>
     * @return The bytes for action.
     */
    com.google.protobuf.ByteString
        getActionBytes();

    /**
     * <pre>
     * 消息摘要
     * </pre>
     *
     * <code>string content = 3;</code>
     * @return The content.
     */
    java.lang.String getContent();
    /**
     * <pre>
     * 消息摘要
     * </pre>
     *
     * <code>string content = 3;</code>
     * @return The bytes for content.
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <pre>
     * 消息发送方ID
     * </pre>
     *
     * <code>string sender = 4;</code>
     * @return The sender.
     */
    java.lang.String getSender();
    /**
     * <pre>
     * 消息发送方ID
     * </pre>
     *
     * <code>string sender = 4;</code>
     * @return The bytes for sender.
     */
    com.google.protobuf.ByteString
        getSenderBytes();

    /**
     * <pre>
     * 消息接收方ID
     * </pre>
     *
     * <code>string receiver = 5;</code>
     * @return The receiver.
     */
    java.lang.String getReceiver();
    /**
     * <pre>
     * 消息接收方ID
     * </pre>
     *
     * <code>string receiver = 5;</code>
     * @return The bytes for receiver.
     */
    com.google.protobuf.ByteString
        getReceiverBytes();

    /**
     * <pre>
     * 消息数据
     * </pre>
     *
     * <code>string extra = 6;</code>
     * @return The extra.
     */
    java.lang.String getExtra();
    /**
     * <pre>
     * 消息数据
     * </pre>
     *
     * <code>string extra = 6;</code>
     * @return The bytes for extra.
     */
    com.google.protobuf.ByteString
        getExtraBytes();

    /**
     * <pre>
     * 消息标题
     * </pre>
     *
     * <code>string title = 7;</code>
     * @return The title.
     */
    java.lang.String getTitle();
    /**
     * <pre>
     * 消息标题
     * </pre>
     *
     * <code>string title = 7;</code>
     * @return The bytes for title.
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <pre>
     * 消息格式
     * </pre>
     *
     * <code>string format = 8;</code>
     * @return The format.
     */
    java.lang.String getFormat();
    /**
     * <pre>
     * 消息格式
     * </pre>
     *
     * <code>string format = 8;</code>
     * @return The bytes for format.
     */
    com.google.protobuf.ByteString
        getFormatBytes();

    /**
     * <pre>
     * 消息发送时间
     * </pre>
     *
     * <code>int64 timestamp = 9;</code>
     * @return The timestamp.
     */
    long getTimestamp();
  }
  /**
   * <pre>
   *自定义消息实体
   * </pre>
   *
   * Protobuf type {@code vip.qsos.im.lib.model.proto.Model}
   */
  public  static final class Model extends
      com.google.protobuf.GeneratedMessageLite<
          Model, Model.Builder> implements
      // @@protoc_insertion_point(message_implements:vip.qsos.im.lib.model.proto.Model)
      ModelOrBuilder {
    private Model() {
      action_ = "";
      content_ = "";
      sender_ = "";
      receiver_ = "";
      extra_ = "";
      title_ = "";
      format_ = "";
    }
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <pre>
     * 消息ID
     * </pre>
     *
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }
    /**
     * <pre>
     * 消息ID
     * </pre>
     *
     * <code>int64 id = 1;</code>
     * @param value The id to set.
     */
    private void setId(long value) {
      
      id_ = value;
    }
    /**
     * <pre>
     * 消息ID
     * </pre>
     *
     * <code>int64 id = 1;</code>
     */
    private void clearId() {
      
      id_ = 0L;
    }

    public static final int ACTION_FIELD_NUMBER = 2;
    private java.lang.String action_;
    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>string action = 2;</code>
     * @return The action.
     */
    @java.lang.Override
    public java.lang.String getAction() {
      return action_;
    }
    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>string action = 2;</code>
     * @return The bytes for action.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getActionBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(action_);
    }
    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>string action = 2;</code>
     * @param value The action to set.
     */
    private void setAction(
        java.lang.String value) {
      value.getClass();
  
      action_ = value;
    }
    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>string action = 2;</code>
     */
    private void clearAction() {
      
      action_ = getDefaultInstance().getAction();
    }
    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>string action = 2;</code>
     * @param value The bytes for action to set.
     */
    private void setActionBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      action_ = value.toStringUtf8();
      
    }

    public static final int CONTENT_FIELD_NUMBER = 3;
    private java.lang.String content_;
    /**
     * <pre>
     * 消息摘要
     * </pre>
     *
     * <code>string content = 3;</code>
     * @return The content.
     */
    @java.lang.Override
    public java.lang.String getContent() {
      return content_;
    }
    /**
     * <pre>
     * 消息摘要
     * </pre>
     *
     * <code>string content = 3;</code>
     * @return The bytes for content.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getContentBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(content_);
    }
    /**
     * <pre>
     * 消息摘要
     * </pre>
     *
     * <code>string content = 3;</code>
     * @param value The content to set.
     */
    private void setContent(
        java.lang.String value) {
      value.getClass();
  
      content_ = value;
    }
    /**
     * <pre>
     * 消息摘要
     * </pre>
     *
     * <code>string content = 3;</code>
     */
    private void clearContent() {
      
      content_ = getDefaultInstance().getContent();
    }
    /**
     * <pre>
     * 消息摘要
     * </pre>
     *
     * <code>string content = 3;</code>
     * @param value The bytes for content to set.
     */
    private void setContentBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      content_ = value.toStringUtf8();
      
    }

    public static final int SENDER_FIELD_NUMBER = 4;
    private java.lang.String sender_;
    /**
     * <pre>
     * 消息发送方ID
     * </pre>
     *
     * <code>string sender = 4;</code>
     * @return The sender.
     */
    @java.lang.Override
    public java.lang.String getSender() {
      return sender_;
    }
    /**
     * <pre>
     * 消息发送方ID
     * </pre>
     *
     * <code>string sender = 4;</code>
     * @return The bytes for sender.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSenderBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(sender_);
    }
    /**
     * <pre>
     * 消息发送方ID
     * </pre>
     *
     * <code>string sender = 4;</code>
     * @param value The sender to set.
     */
    private void setSender(
        java.lang.String value) {
      value.getClass();
  
      sender_ = value;
    }
    /**
     * <pre>
     * 消息发送方ID
     * </pre>
     *
     * <code>string sender = 4;</code>
     */
    private void clearSender() {
      
      sender_ = getDefaultInstance().getSender();
    }
    /**
     * <pre>
     * 消息发送方ID
     * </pre>
     *
     * <code>string sender = 4;</code>
     * @param value The bytes for sender to set.
     */
    private void setSenderBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      sender_ = value.toStringUtf8();
      
    }

    public static final int RECEIVER_FIELD_NUMBER = 5;
    private java.lang.String receiver_;
    /**
     * <pre>
     * 消息接收方ID
     * </pre>
     *
     * <code>string receiver = 5;</code>
     * @return The receiver.
     */
    @java.lang.Override
    public java.lang.String getReceiver() {
      return receiver_;
    }
    /**
     * <pre>
     * 消息接收方ID
     * </pre>
     *
     * <code>string receiver = 5;</code>
     * @return The bytes for receiver.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getReceiverBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(receiver_);
    }
    /**
     * <pre>
     * 消息接收方ID
     * </pre>
     *
     * <code>string receiver = 5;</code>
     * @param value The receiver to set.
     */
    private void setReceiver(
        java.lang.String value) {
      value.getClass();
  
      receiver_ = value;
    }
    /**
     * <pre>
     * 消息接收方ID
     * </pre>
     *
     * <code>string receiver = 5;</code>
     */
    private void clearReceiver() {
      
      receiver_ = getDefaultInstance().getReceiver();
    }
    /**
     * <pre>
     * 消息接收方ID
     * </pre>
     *
     * <code>string receiver = 5;</code>
     * @param value The bytes for receiver to set.
     */
    private void setReceiverBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      receiver_ = value.toStringUtf8();
      
    }

    public static final int EXTRA_FIELD_NUMBER = 6;
    private java.lang.String extra_;
    /**
     * <pre>
     * 消息数据
     * </pre>
     *
     * <code>string extra = 6;</code>
     * @return The extra.
     */
    @java.lang.Override
    public java.lang.String getExtra() {
      return extra_;
    }
    /**
     * <pre>
     * 消息数据
     * </pre>
     *
     * <code>string extra = 6;</code>
     * @return The bytes for extra.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getExtraBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(extra_);
    }
    /**
     * <pre>
     * 消息数据
     * </pre>
     *
     * <code>string extra = 6;</code>
     * @param value The extra to set.
     */
    private void setExtra(
        java.lang.String value) {
      value.getClass();
  
      extra_ = value;
    }
    /**
     * <pre>
     * 消息数据
     * </pre>
     *
     * <code>string extra = 6;</code>
     */
    private void clearExtra() {
      
      extra_ = getDefaultInstance().getExtra();
    }
    /**
     * <pre>
     * 消息数据
     * </pre>
     *
     * <code>string extra = 6;</code>
     * @param value The bytes for extra to set.
     */
    private void setExtraBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      extra_ = value.toStringUtf8();
      
    }

    public static final int TITLE_FIELD_NUMBER = 7;
    private java.lang.String title_;
    /**
     * <pre>
     * 消息标题
     * </pre>
     *
     * <code>string title = 7;</code>
     * @return The title.
     */
    @java.lang.Override
    public java.lang.String getTitle() {
      return title_;
    }
    /**
     * <pre>
     * 消息标题
     * </pre>
     *
     * <code>string title = 7;</code>
     * @return The bytes for title.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTitleBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(title_);
    }
    /**
     * <pre>
     * 消息标题
     * </pre>
     *
     * <code>string title = 7;</code>
     * @param value The title to set.
     */
    private void setTitle(
        java.lang.String value) {
      value.getClass();
  
      title_ = value;
    }
    /**
     * <pre>
     * 消息标题
     * </pre>
     *
     * <code>string title = 7;</code>
     */
    private void clearTitle() {
      
      title_ = getDefaultInstance().getTitle();
    }
    /**
     * <pre>
     * 消息标题
     * </pre>
     *
     * <code>string title = 7;</code>
     * @param value The bytes for title to set.
     */
    private void setTitleBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      title_ = value.toStringUtf8();
      
    }

    public static final int FORMAT_FIELD_NUMBER = 8;
    private java.lang.String format_;
    /**
     * <pre>
     * 消息格式
     * </pre>
     *
     * <code>string format = 8;</code>
     * @return The format.
     */
    @java.lang.Override
    public java.lang.String getFormat() {
      return format_;
    }
    /**
     * <pre>
     * 消息格式
     * </pre>
     *
     * <code>string format = 8;</code>
     * @return The bytes for format.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFormatBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(format_);
    }
    /**
     * <pre>
     * 消息格式
     * </pre>
     *
     * <code>string format = 8;</code>
     * @param value The format to set.
     */
    private void setFormat(
        java.lang.String value) {
      value.getClass();
  
      format_ = value;
    }
    /**
     * <pre>
     * 消息格式
     * </pre>
     *
     * <code>string format = 8;</code>
     */
    private void clearFormat() {
      
      format_ = getDefaultInstance().getFormat();
    }
    /**
     * <pre>
     * 消息格式
     * </pre>
     *
     * <code>string format = 8;</code>
     * @param value The bytes for format to set.
     */
    private void setFormatBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      format_ = value.toStringUtf8();
      
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 9;
    private long timestamp_;
    /**
     * <pre>
     * 消息发送时间
     * </pre>
     *
     * <code>int64 timestamp = 9;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <pre>
     * 消息发送时间
     * </pre>
     *
     * <code>int64 timestamp = 9;</code>
     * @param value The timestamp to set.
     */
    private void setTimestamp(long value) {
      
      timestamp_ = value;
    }
    /**
     * <pre>
     * 消息发送时间
     * </pre>
     *
     * <code>int64 timestamp = 9;</code>
     */
    private void clearTimestamp() {
      
      timestamp_ = 0L;
    }

    public static vip.qsos.im.lib.model.proto.MessageProto.Model parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static vip.qsos.im.lib.model.proto.MessageProto.Model parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static vip.qsos.im.lib.model.proto.MessageProto.Model parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static vip.qsos.im.lib.model.proto.MessageProto.Model parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static vip.qsos.im.lib.model.proto.MessageProto.Model parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static vip.qsos.im.lib.model.proto.MessageProto.Model parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static vip.qsos.im.lib.model.proto.MessageProto.Model parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static vip.qsos.im.lib.model.proto.MessageProto.Model parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static vip.qsos.im.lib.model.proto.MessageProto.Model parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static vip.qsos.im.lib.model.proto.MessageProto.Model parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static vip.qsos.im.lib.model.proto.MessageProto.Model parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static vip.qsos.im.lib.model.proto.MessageProto.Model parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(vip.qsos.im.lib.model.proto.MessageProto.Model prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     *自定义消息实体
     * </pre>
     *
     * Protobuf type {@code vip.qsos.im.lib.model.proto.Model}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          vip.qsos.im.lib.model.proto.MessageProto.Model, Builder> implements
        // @@protoc_insertion_point(builder_implements:vip.qsos.im.lib.model.proto.Model)
        vip.qsos.im.lib.model.proto.MessageProto.ModelOrBuilder {
      // Construct using vip.qsos.im.lib.model.proto.MessageProto.Model.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * 消息ID
       * </pre>
       *
       * <code>int64 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public long getId() {
        return instance.getId();
      }
      /**
       * <pre>
       * 消息ID
       * </pre>
       *
       * <code>int64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {
        copyOnWrite();
        instance.setId(value);
        return this;
      }
      /**
       * <pre>
       * 消息ID
       * </pre>
       *
       * <code>int64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        copyOnWrite();
        instance.clearId();
        return this;
      }

      /**
       * <pre>
       * 消息类型
       * </pre>
       *
       * <code>string action = 2;</code>
       * @return The action.
       */
      @java.lang.Override
      public java.lang.String getAction() {
        return instance.getAction();
      }
      /**
       * <pre>
       * 消息类型
       * </pre>
       *
       * <code>string action = 2;</code>
       * @return The bytes for action.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getActionBytes() {
        return instance.getActionBytes();
      }
      /**
       * <pre>
       * 消息类型
       * </pre>
       *
       * <code>string action = 2;</code>
       * @param value The action to set.
       * @return This builder for chaining.
       */
      public Builder setAction(
          java.lang.String value) {
        copyOnWrite();
        instance.setAction(value);
        return this;
      }
      /**
       * <pre>
       * 消息类型
       * </pre>
       *
       * <code>string action = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAction() {
        copyOnWrite();
        instance.clearAction();
        return this;
      }
      /**
       * <pre>
       * 消息类型
       * </pre>
       *
       * <code>string action = 2;</code>
       * @param value The bytes for action to set.
       * @return This builder for chaining.
       */
      public Builder setActionBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setActionBytes(value);
        return this;
      }

      /**
       * <pre>
       * 消息摘要
       * </pre>
       *
       * <code>string content = 3;</code>
       * @return The content.
       */
      @java.lang.Override
      public java.lang.String getContent() {
        return instance.getContent();
      }
      /**
       * <pre>
       * 消息摘要
       * </pre>
       *
       * <code>string content = 3;</code>
       * @return The bytes for content.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getContentBytes() {
        return instance.getContentBytes();
      }
      /**
       * <pre>
       * 消息摘要
       * </pre>
       *
       * <code>string content = 3;</code>
       * @param value The content to set.
       * @return This builder for chaining.
       */
      public Builder setContent(
          java.lang.String value) {
        copyOnWrite();
        instance.setContent(value);
        return this;
      }
      /**
       * <pre>
       * 消息摘要
       * </pre>
       *
       * <code>string content = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearContent() {
        copyOnWrite();
        instance.clearContent();
        return this;
      }
      /**
       * <pre>
       * 消息摘要
       * </pre>
       *
       * <code>string content = 3;</code>
       * @param value The bytes for content to set.
       * @return This builder for chaining.
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setContentBytes(value);
        return this;
      }

      /**
       * <pre>
       * 消息发送方ID
       * </pre>
       *
       * <code>string sender = 4;</code>
       * @return The sender.
       */
      @java.lang.Override
      public java.lang.String getSender() {
        return instance.getSender();
      }
      /**
       * <pre>
       * 消息发送方ID
       * </pre>
       *
       * <code>string sender = 4;</code>
       * @return The bytes for sender.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getSenderBytes() {
        return instance.getSenderBytes();
      }
      /**
       * <pre>
       * 消息发送方ID
       * </pre>
       *
       * <code>string sender = 4;</code>
       * @param value The sender to set.
       * @return This builder for chaining.
       */
      public Builder setSender(
          java.lang.String value) {
        copyOnWrite();
        instance.setSender(value);
        return this;
      }
      /**
       * <pre>
       * 消息发送方ID
       * </pre>
       *
       * <code>string sender = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearSender() {
        copyOnWrite();
        instance.clearSender();
        return this;
      }
      /**
       * <pre>
       * 消息发送方ID
       * </pre>
       *
       * <code>string sender = 4;</code>
       * @param value The bytes for sender to set.
       * @return This builder for chaining.
       */
      public Builder setSenderBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSenderBytes(value);
        return this;
      }

      /**
       * <pre>
       * 消息接收方ID
       * </pre>
       *
       * <code>string receiver = 5;</code>
       * @return The receiver.
       */
      @java.lang.Override
      public java.lang.String getReceiver() {
        return instance.getReceiver();
      }
      /**
       * <pre>
       * 消息接收方ID
       * </pre>
       *
       * <code>string receiver = 5;</code>
       * @return The bytes for receiver.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getReceiverBytes() {
        return instance.getReceiverBytes();
      }
      /**
       * <pre>
       * 消息接收方ID
       * </pre>
       *
       * <code>string receiver = 5;</code>
       * @param value The receiver to set.
       * @return This builder for chaining.
       */
      public Builder setReceiver(
          java.lang.String value) {
        copyOnWrite();
        instance.setReceiver(value);
        return this;
      }
      /**
       * <pre>
       * 消息接收方ID
       * </pre>
       *
       * <code>string receiver = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearReceiver() {
        copyOnWrite();
        instance.clearReceiver();
        return this;
      }
      /**
       * <pre>
       * 消息接收方ID
       * </pre>
       *
       * <code>string receiver = 5;</code>
       * @param value The bytes for receiver to set.
       * @return This builder for chaining.
       */
      public Builder setReceiverBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setReceiverBytes(value);
        return this;
      }

      /**
       * <pre>
       * 消息数据
       * </pre>
       *
       * <code>string extra = 6;</code>
       * @return The extra.
       */
      @java.lang.Override
      public java.lang.String getExtra() {
        return instance.getExtra();
      }
      /**
       * <pre>
       * 消息数据
       * </pre>
       *
       * <code>string extra = 6;</code>
       * @return The bytes for extra.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getExtraBytes() {
        return instance.getExtraBytes();
      }
      /**
       * <pre>
       * 消息数据
       * </pre>
       *
       * <code>string extra = 6;</code>
       * @param value The extra to set.
       * @return This builder for chaining.
       */
      public Builder setExtra(
          java.lang.String value) {
        copyOnWrite();
        instance.setExtra(value);
        return this;
      }
      /**
       * <pre>
       * 消息数据
       * </pre>
       *
       * <code>string extra = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearExtra() {
        copyOnWrite();
        instance.clearExtra();
        return this;
      }
      /**
       * <pre>
       * 消息数据
       * </pre>
       *
       * <code>string extra = 6;</code>
       * @param value The bytes for extra to set.
       * @return This builder for chaining.
       */
      public Builder setExtraBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setExtraBytes(value);
        return this;
      }

      /**
       * <pre>
       * 消息标题
       * </pre>
       *
       * <code>string title = 7;</code>
       * @return The title.
       */
      @java.lang.Override
      public java.lang.String getTitle() {
        return instance.getTitle();
      }
      /**
       * <pre>
       * 消息标题
       * </pre>
       *
       * <code>string title = 7;</code>
       * @return The bytes for title.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getTitleBytes() {
        return instance.getTitleBytes();
      }
      /**
       * <pre>
       * 消息标题
       * </pre>
       *
       * <code>string title = 7;</code>
       * @param value The title to set.
       * @return This builder for chaining.
       */
      public Builder setTitle(
          java.lang.String value) {
        copyOnWrite();
        instance.setTitle(value);
        return this;
      }
      /**
       * <pre>
       * 消息标题
       * </pre>
       *
       * <code>string title = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearTitle() {
        copyOnWrite();
        instance.clearTitle();
        return this;
      }
      /**
       * <pre>
       * 消息标题
       * </pre>
       *
       * <code>string title = 7;</code>
       * @param value The bytes for title to set.
       * @return This builder for chaining.
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setTitleBytes(value);
        return this;
      }

      /**
       * <pre>
       * 消息格式
       * </pre>
       *
       * <code>string format = 8;</code>
       * @return The format.
       */
      @java.lang.Override
      public java.lang.String getFormat() {
        return instance.getFormat();
      }
      /**
       * <pre>
       * 消息格式
       * </pre>
       *
       * <code>string format = 8;</code>
       * @return The bytes for format.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getFormatBytes() {
        return instance.getFormatBytes();
      }
      /**
       * <pre>
       * 消息格式
       * </pre>
       *
       * <code>string format = 8;</code>
       * @param value The format to set.
       * @return This builder for chaining.
       */
      public Builder setFormat(
          java.lang.String value) {
        copyOnWrite();
        instance.setFormat(value);
        return this;
      }
      /**
       * <pre>
       * 消息格式
       * </pre>
       *
       * <code>string format = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearFormat() {
        copyOnWrite();
        instance.clearFormat();
        return this;
      }
      /**
       * <pre>
       * 消息格式
       * </pre>
       *
       * <code>string format = 8;</code>
       * @param value The bytes for format to set.
       * @return This builder for chaining.
       */
      public Builder setFormatBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setFormatBytes(value);
        return this;
      }

      /**
       * <pre>
       * 消息发送时间
       * </pre>
       *
       * <code>int64 timestamp = 9;</code>
       * @return The timestamp.
       */
      @java.lang.Override
      public long getTimestamp() {
        return instance.getTimestamp();
      }
      /**
       * <pre>
       * 消息发送时间
       * </pre>
       *
       * <code>int64 timestamp = 9;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {
        copyOnWrite();
        instance.setTimestamp(value);
        return this;
      }
      /**
       * <pre>
       * 消息发送时间
       * </pre>
       *
       * <code>int64 timestamp = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        copyOnWrite();
        instance.clearTimestamp();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:vip.qsos.im.lib.model.proto.Model)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new vip.qsos.im.lib.model.proto.MessageProto.Model();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "id_",
              "action_",
              "content_",
              "sender_",
              "receiver_",
              "extra_",
              "title_",
              "format_",
              "timestamp_",
            };
            java.lang.String info =
                "\u0000\t\u0000\u0000\u0001\t\t\u0000\u0000\u0000\u0001\u0002\u0002\u0208\u0003\u0208" +
                "\u0004\u0208\u0005\u0208\u0006\u0208\u0007\u0208\b\u0208\t\u0002";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<vip.qsos.im.lib.model.proto.MessageProto.Model> parser = PARSER;
          if (parser == null) {
            synchronized (vip.qsos.im.lib.model.proto.MessageProto.Model.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<vip.qsos.im.lib.model.proto.MessageProto.Model>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:vip.qsos.im.lib.model.proto.Model)
    private static final vip.qsos.im.lib.model.proto.MessageProto.Model DEFAULT_INSTANCE;
    static {
      Model defaultInstance = new Model();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        Model.class, defaultInstance);
    }

    public static vip.qsos.im.lib.model.proto.MessageProto.Model getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Model> PARSER;

    public static com.google.protobuf.Parser<Model> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
