// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Session.proto

package vip.qsos.im.lib.model.proto;

public final class SessionProto {
  private SessionProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface ModelOrBuilder extends
      // @@protoc_insertion_point(interface_extends:vip.qsos.im.lib.model.proto.Model)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     *数据库主键ID
     * </pre>
     *
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    long getId();

    /**
     * <pre>
     *session绑定的用户账号
     * </pre>
     *
     * <code>string account = 2;</code>
     * @return The account.
     */
    java.lang.String getAccount();
    /**
     * <pre>
     *session绑定的用户账号
     * </pre>
     *
     * <code>string account = 2;</code>
     * @return The bytes for account.
     */
    com.google.protobuf.ByteString
        getAccountBytes();

    /**
     * <pre>
     *session在本台服务器上的ID
     * </pre>
     *
     * <code>string nid = 3;</code>
     * @return The nid.
     */
    java.lang.String getNid();
    /**
     * <pre>
     *session在本台服务器上的ID
     * </pre>
     *
     * <code>string nid = 3;</code>
     * @return The bytes for nid.
     */
    com.google.protobuf.ByteString
        getNidBytes();

    /**
     * <pre>
     *客户端 ID (设备号码+应用包名),ios为 device token 
     * </pre>
     *
     * <code>string deviceId = 4;</code>
     * @return The deviceId.
     */
    java.lang.String getDeviceId();
    /**
     * <pre>
     *客户端 ID (设备号码+应用包名),ios为 device token 
     * </pre>
     *
     * <code>string deviceId = 4;</code>
     * @return The bytes for deviceId.
     */
    com.google.protobuf.ByteString
        getDeviceIdBytes();

    /**
     * <pre>
     *session绑定的服务器IP
     * </pre>
     *
     * <code>string host = 5;</code>
     * @return The host.
     */
    java.lang.String getHost();
    /**
     * <pre>
     *session绑定的服务器IP
     * </pre>
     *
     * <code>string host = 5;</code>
     * @return The bytes for host.
     */
    com.google.protobuf.ByteString
        getHostBytes();

    /**
     * <pre>
     *客户端设备类型
     * </pre>
     *
     * <code>string channel = 6;</code>
     * @return The channel.
     */
    java.lang.String getChannel();
    /**
     * <pre>
     *客户端设备类型
     * </pre>
     *
     * <code>string channel = 6;</code>
     * @return The bytes for channel.
     */
    com.google.protobuf.ByteString
        getChannelBytes();

    /**
     * <pre>
     *客户端设备型号
     * </pre>
     *
     * <code>string deviceModel = 7;</code>
     * @return The deviceModel.
     */
    java.lang.String getDeviceModel();
    /**
     * <pre>
     *客户端设备型号
     * </pre>
     *
     * <code>string deviceModel = 7;</code>
     * @return The bytes for deviceModel.
     */
    com.google.protobuf.ByteString
        getDeviceModelBytes();

    /**
     * <pre>
     *客户端应用版本
     * </pre>
     *
     * <code>string clientVersion = 8;</code>
     * @return The clientVersion.
     */
    java.lang.String getClientVersion();
    /**
     * <pre>
     *客户端应用版本
     * </pre>
     *
     * <code>string clientVersion = 8;</code>
     * @return The bytes for clientVersion.
     */
    com.google.protobuf.ByteString
        getClientVersionBytes();

    /**
     * <pre>
     *客户端系统版本
     * </pre>
     *
     * <code>string systemVersion = 9;</code>
     * @return The systemVersion.
     */
    java.lang.String getSystemVersion();
    /**
     * <pre>
     *客户端系统版本
     * </pre>
     *
     * <code>string systemVersion = 9;</code>
     * @return The bytes for systemVersion.
     */
    com.google.protobuf.ByteString
        getSystemVersionBytes();

    /**
     * <pre>
     *客户端登录时间
     * </pre>
     *
     * <code>int64 bindTime = 10;</code>
     * @return The bindTime.
     */
    long getBindTime();

    /**
     * <pre>
     *客户端经度
     * </pre>
     *
     * <code>double longitude = 11;</code>
     * @return The longitude.
     */
    double getLongitude();

    /**
     * <pre>
     *客户端维度
     * </pre>
     *
     * <code>double latitude = 12;</code>
     * @return The latitude.
     */
    double getLatitude();

    /**
     * <pre>
     *客户端位置
     * </pre>
     *
     * <code>string location = 13;</code>
     * @return The location.
     */
    java.lang.String getLocation();
    /**
     * <pre>
     *客户端位置
     * </pre>
     *
     * <code>string location = 13;</code>
     * @return The bytes for location.
     */
    com.google.protobuf.ByteString
        getLocationBytes();

    /**
     * <pre>
     *apns推送状态
     * </pre>
     *
     * <code>int32 apns = 14;</code>
     * @return The apns.
     */
    int getApns();

    /**
     * <pre>
     *客户端在线状态
     * </pre>
     *
     * <code>int32 state = 15;</code>
     * @return The state.
     */
    int getState();
  }
  /**
   * <pre>
   *消息会话包装类
   * </pre>
   *
   * Protobuf type {@code vip.qsos.im.lib.model.proto.Model}
   */
  public  static final class Model extends
      com.google.protobuf.GeneratedMessageLite<
          Model, Model.Builder> implements
      // @@protoc_insertion_point(message_implements:vip.qsos.im.lib.model.proto.Model)
      ModelOrBuilder {
    private Model() {
      account_ = "";
      nid_ = "";
      deviceId_ = "";
      host_ = "";
      channel_ = "";
      deviceModel_ = "";
      clientVersion_ = "";
      systemVersion_ = "";
      location_ = "";
    }
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <pre>
     *数据库主键ID
     * </pre>
     *
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }
    /**
     * <pre>
     *数据库主键ID
     * </pre>
     *
     * <code>int64 id = 1;</code>
     * @param value The id to set.
     */
    private void setId(long value) {
      
      id_ = value;
    }
    /**
     * <pre>
     *数据库主键ID
     * </pre>
     *
     * <code>int64 id = 1;</code>
     */
    private void clearId() {
      
      id_ = 0L;
    }

    public static final int ACCOUNT_FIELD_NUMBER = 2;
    private java.lang.String account_;
    /**
     * <pre>
     *session绑定的用户账号
     * </pre>
     *
     * <code>string account = 2;</code>
     * @return The account.
     */
    @java.lang.Override
    public java.lang.String getAccount() {
      return account_;
    }
    /**
     * <pre>
     *session绑定的用户账号
     * </pre>
     *
     * <code>string account = 2;</code>
     * @return The bytes for account.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAccountBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(account_);
    }
    /**
     * <pre>
     *session绑定的用户账号
     * </pre>
     *
     * <code>string account = 2;</code>
     * @param value The account to set.
     */
    private void setAccount(
        java.lang.String value) {
      value.getClass();
  
      account_ = value;
    }
    /**
     * <pre>
     *session绑定的用户账号
     * </pre>
     *
     * <code>string account = 2;</code>
     */
    private void clearAccount() {
      
      account_ = getDefaultInstance().getAccount();
    }
    /**
     * <pre>
     *session绑定的用户账号
     * </pre>
     *
     * <code>string account = 2;</code>
     * @param value The bytes for account to set.
     */
    private void setAccountBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      account_ = value.toStringUtf8();
      
    }

    public static final int NID_FIELD_NUMBER = 3;
    private java.lang.String nid_;
    /**
     * <pre>
     *session在本台服务器上的ID
     * </pre>
     *
     * <code>string nid = 3;</code>
     * @return The nid.
     */
    @java.lang.Override
    public java.lang.String getNid() {
      return nid_;
    }
    /**
     * <pre>
     *session在本台服务器上的ID
     * </pre>
     *
     * <code>string nid = 3;</code>
     * @return The bytes for nid.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNidBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(nid_);
    }
    /**
     * <pre>
     *session在本台服务器上的ID
     * </pre>
     *
     * <code>string nid = 3;</code>
     * @param value The nid to set.
     */
    private void setNid(
        java.lang.String value) {
      value.getClass();
  
      nid_ = value;
    }
    /**
     * <pre>
     *session在本台服务器上的ID
     * </pre>
     *
     * <code>string nid = 3;</code>
     */
    private void clearNid() {
      
      nid_ = getDefaultInstance().getNid();
    }
    /**
     * <pre>
     *session在本台服务器上的ID
     * </pre>
     *
     * <code>string nid = 3;</code>
     * @param value The bytes for nid to set.
     */
    private void setNidBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      nid_ = value.toStringUtf8();
      
    }

    public static final int DEVICEID_FIELD_NUMBER = 4;
    private java.lang.String deviceId_;
    /**
     * <pre>
     *客户端 ID (设备号码+应用包名),ios为 device token 
     * </pre>
     *
     * <code>string deviceId = 4;</code>
     * @return The deviceId.
     */
    @java.lang.Override
    public java.lang.String getDeviceId() {
      return deviceId_;
    }
    /**
     * <pre>
     *客户端 ID (设备号码+应用包名),ios为 device token 
     * </pre>
     *
     * <code>string deviceId = 4;</code>
     * @return The bytes for deviceId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(deviceId_);
    }
    /**
     * <pre>
     *客户端 ID (设备号码+应用包名),ios为 device token 
     * </pre>
     *
     * <code>string deviceId = 4;</code>
     * @param value The deviceId to set.
     */
    private void setDeviceId(
        java.lang.String value) {
      value.getClass();
  
      deviceId_ = value;
    }
    /**
     * <pre>
     *客户端 ID (设备号码+应用包名),ios为 device token 
     * </pre>
     *
     * <code>string deviceId = 4;</code>
     */
    private void clearDeviceId() {
      
      deviceId_ = getDefaultInstance().getDeviceId();
    }
    /**
     * <pre>
     *客户端 ID (设备号码+应用包名),ios为 device token 
     * </pre>
     *
     * <code>string deviceId = 4;</code>
     * @param value The bytes for deviceId to set.
     */
    private void setDeviceIdBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      deviceId_ = value.toStringUtf8();
      
    }

    public static final int HOST_FIELD_NUMBER = 5;
    private java.lang.String host_;
    /**
     * <pre>
     *session绑定的服务器IP
     * </pre>
     *
     * <code>string host = 5;</code>
     * @return The host.
     */
    @java.lang.Override
    public java.lang.String getHost() {
      return host_;
    }
    /**
     * <pre>
     *session绑定的服务器IP
     * </pre>
     *
     * <code>string host = 5;</code>
     * @return The bytes for host.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getHostBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(host_);
    }
    /**
     * <pre>
     *session绑定的服务器IP
     * </pre>
     *
     * <code>string host = 5;</code>
     * @param value The host to set.
     */
    private void setHost(
        java.lang.String value) {
      value.getClass();
  
      host_ = value;
    }
    /**
     * <pre>
     *session绑定的服务器IP
     * </pre>
     *
     * <code>string host = 5;</code>
     */
    private void clearHost() {
      
      host_ = getDefaultInstance().getHost();
    }
    /**
     * <pre>
     *session绑定的服务器IP
     * </pre>
     *
     * <code>string host = 5;</code>
     * @param value The bytes for host to set.
     */
    private void setHostBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      host_ = value.toStringUtf8();
      
    }

    public static final int CHANNEL_FIELD_NUMBER = 6;
    private java.lang.String channel_;
    /**
     * <pre>
     *客户端设备类型
     * </pre>
     *
     * <code>string channel = 6;</code>
     * @return The channel.
     */
    @java.lang.Override
    public java.lang.String getChannel() {
      return channel_;
    }
    /**
     * <pre>
     *客户端设备类型
     * </pre>
     *
     * <code>string channel = 6;</code>
     * @return The bytes for channel.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getChannelBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(channel_);
    }
    /**
     * <pre>
     *客户端设备类型
     * </pre>
     *
     * <code>string channel = 6;</code>
     * @param value The channel to set.
     */
    private void setChannel(
        java.lang.String value) {
      value.getClass();
  
      channel_ = value;
    }
    /**
     * <pre>
     *客户端设备类型
     * </pre>
     *
     * <code>string channel = 6;</code>
     */
    private void clearChannel() {
      
      channel_ = getDefaultInstance().getChannel();
    }
    /**
     * <pre>
     *客户端设备类型
     * </pre>
     *
     * <code>string channel = 6;</code>
     * @param value The bytes for channel to set.
     */
    private void setChannelBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      channel_ = value.toStringUtf8();
      
    }

    public static final int DEVICEMODEL_FIELD_NUMBER = 7;
    private java.lang.String deviceModel_;
    /**
     * <pre>
     *客户端设备型号
     * </pre>
     *
     * <code>string deviceModel = 7;</code>
     * @return The deviceModel.
     */
    @java.lang.Override
    public java.lang.String getDeviceModel() {
      return deviceModel_;
    }
    /**
     * <pre>
     *客户端设备型号
     * </pre>
     *
     * <code>string deviceModel = 7;</code>
     * @return The bytes for deviceModel.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDeviceModelBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(deviceModel_);
    }
    /**
     * <pre>
     *客户端设备型号
     * </pre>
     *
     * <code>string deviceModel = 7;</code>
     * @param value The deviceModel to set.
     */
    private void setDeviceModel(
        java.lang.String value) {
      value.getClass();
  
      deviceModel_ = value;
    }
    /**
     * <pre>
     *客户端设备型号
     * </pre>
     *
     * <code>string deviceModel = 7;</code>
     */
    private void clearDeviceModel() {
      
      deviceModel_ = getDefaultInstance().getDeviceModel();
    }
    /**
     * <pre>
     *客户端设备型号
     * </pre>
     *
     * <code>string deviceModel = 7;</code>
     * @param value The bytes for deviceModel to set.
     */
    private void setDeviceModelBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      deviceModel_ = value.toStringUtf8();
      
    }

    public static final int CLIENTVERSION_FIELD_NUMBER = 8;
    private java.lang.String clientVersion_;
    /**
     * <pre>
     *客户端应用版本
     * </pre>
     *
     * <code>string clientVersion = 8;</code>
     * @return The clientVersion.
     */
    @java.lang.Override
    public java.lang.String getClientVersion() {
      return clientVersion_;
    }
    /**
     * <pre>
     *客户端应用版本
     * </pre>
     *
     * <code>string clientVersion = 8;</code>
     * @return The bytes for clientVersion.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getClientVersionBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(clientVersion_);
    }
    /**
     * <pre>
     *客户端应用版本
     * </pre>
     *
     * <code>string clientVersion = 8;</code>
     * @param value The clientVersion to set.
     */
    private void setClientVersion(
        java.lang.String value) {
      value.getClass();
  
      clientVersion_ = value;
    }
    /**
     * <pre>
     *客户端应用版本
     * </pre>
     *
     * <code>string clientVersion = 8;</code>
     */
    private void clearClientVersion() {
      
      clientVersion_ = getDefaultInstance().getClientVersion();
    }
    /**
     * <pre>
     *客户端应用版本
     * </pre>
     *
     * <code>string clientVersion = 8;</code>
     * @param value The bytes for clientVersion to set.
     */
    private void setClientVersionBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      clientVersion_ = value.toStringUtf8();
      
    }

    public static final int SYSTEMVERSION_FIELD_NUMBER = 9;
    private java.lang.String systemVersion_;
    /**
     * <pre>
     *客户端系统版本
     * </pre>
     *
     * <code>string systemVersion = 9;</code>
     * @return The systemVersion.
     */
    @java.lang.Override
    public java.lang.String getSystemVersion() {
      return systemVersion_;
    }
    /**
     * <pre>
     *客户端系统版本
     * </pre>
     *
     * <code>string systemVersion = 9;</code>
     * @return The bytes for systemVersion.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSystemVersionBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(systemVersion_);
    }
    /**
     * <pre>
     *客户端系统版本
     * </pre>
     *
     * <code>string systemVersion = 9;</code>
     * @param value The systemVersion to set.
     */
    private void setSystemVersion(
        java.lang.String value) {
      value.getClass();
  
      systemVersion_ = value;
    }
    /**
     * <pre>
     *客户端系统版本
     * </pre>
     *
     * <code>string systemVersion = 9;</code>
     */
    private void clearSystemVersion() {
      
      systemVersion_ = getDefaultInstance().getSystemVersion();
    }
    /**
     * <pre>
     *客户端系统版本
     * </pre>
     *
     * <code>string systemVersion = 9;</code>
     * @param value The bytes for systemVersion to set.
     */
    private void setSystemVersionBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      systemVersion_ = value.toStringUtf8();
      
    }

    public static final int BINDTIME_FIELD_NUMBER = 10;
    private long bindTime_;
    /**
     * <pre>
     *客户端登录时间
     * </pre>
     *
     * <code>int64 bindTime = 10;</code>
     * @return The bindTime.
     */
    @java.lang.Override
    public long getBindTime() {
      return bindTime_;
    }
    /**
     * <pre>
     *客户端登录时间
     * </pre>
     *
     * <code>int64 bindTime = 10;</code>
     * @param value The bindTime to set.
     */
    private void setBindTime(long value) {
      
      bindTime_ = value;
    }
    /**
     * <pre>
     *客户端登录时间
     * </pre>
     *
     * <code>int64 bindTime = 10;</code>
     */
    private void clearBindTime() {
      
      bindTime_ = 0L;
    }

    public static final int LONGITUDE_FIELD_NUMBER = 11;
    private double longitude_;
    /**
     * <pre>
     *客户端经度
     * </pre>
     *
     * <code>double longitude = 11;</code>
     * @return The longitude.
     */
    @java.lang.Override
    public double getLongitude() {
      return longitude_;
    }
    /**
     * <pre>
     *客户端经度
     * </pre>
     *
     * <code>double longitude = 11;</code>
     * @param value The longitude to set.
     */
    private void setLongitude(double value) {
      
      longitude_ = value;
    }
    /**
     * <pre>
     *客户端经度
     * </pre>
     *
     * <code>double longitude = 11;</code>
     */
    private void clearLongitude() {
      
      longitude_ = 0D;
    }

    public static final int LATITUDE_FIELD_NUMBER = 12;
    private double latitude_;
    /**
     * <pre>
     *客户端维度
     * </pre>
     *
     * <code>double latitude = 12;</code>
     * @return The latitude.
     */
    @java.lang.Override
    public double getLatitude() {
      return latitude_;
    }
    /**
     * <pre>
     *客户端维度
     * </pre>
     *
     * <code>double latitude = 12;</code>
     * @param value The latitude to set.
     */
    private void setLatitude(double value) {
      
      latitude_ = value;
    }
    /**
     * <pre>
     *客户端维度
     * </pre>
     *
     * <code>double latitude = 12;</code>
     */
    private void clearLatitude() {
      
      latitude_ = 0D;
    }

    public static final int LOCATION_FIELD_NUMBER = 13;
    private java.lang.String location_;
    /**
     * <pre>
     *客户端位置
     * </pre>
     *
     * <code>string location = 13;</code>
     * @return The location.
     */
    @java.lang.Override
    public java.lang.String getLocation() {
      return location_;
    }
    /**
     * <pre>
     *客户端位置
     * </pre>
     *
     * <code>string location = 13;</code>
     * @return The bytes for location.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLocationBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(location_);
    }
    /**
     * <pre>
     *客户端位置
     * </pre>
     *
     * <code>string location = 13;</code>
     * @param value The location to set.
     */
    private void setLocation(
        java.lang.String value) {
      value.getClass();
  
      location_ = value;
    }
    /**
     * <pre>
     *客户端位置
     * </pre>
     *
     * <code>string location = 13;</code>
     */
    private void clearLocation() {
      
      location_ = getDefaultInstance().getLocation();
    }
    /**
     * <pre>
     *客户端位置
     * </pre>
     *
     * <code>string location = 13;</code>
     * @param value The bytes for location to set.
     */
    private void setLocationBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      location_ = value.toStringUtf8();
      
    }

    public static final int APNS_FIELD_NUMBER = 14;
    private int apns_;
    /**
     * <pre>
     *apns推送状态
     * </pre>
     *
     * <code>int32 apns = 14;</code>
     * @return The apns.
     */
    @java.lang.Override
    public int getApns() {
      return apns_;
    }
    /**
     * <pre>
     *apns推送状态
     * </pre>
     *
     * <code>int32 apns = 14;</code>
     * @param value The apns to set.
     */
    private void setApns(int value) {
      
      apns_ = value;
    }
    /**
     * <pre>
     *apns推送状态
     * </pre>
     *
     * <code>int32 apns = 14;</code>
     */
    private void clearApns() {
      
      apns_ = 0;
    }

    public static final int STATE_FIELD_NUMBER = 15;
    private int state_;
    /**
     * <pre>
     *客户端在线状态
     * </pre>
     *
     * <code>int32 state = 15;</code>
     * @return The state.
     */
    @java.lang.Override
    public int getState() {
      return state_;
    }
    /**
     * <pre>
     *客户端在线状态
     * </pre>
     *
     * <code>int32 state = 15;</code>
     * @param value The state to set.
     */
    private void setState(int value) {
      
      state_ = value;
    }
    /**
     * <pre>
     *客户端在线状态
     * </pre>
     *
     * <code>int32 state = 15;</code>
     */
    private void clearState() {
      
      state_ = 0;
    }

    public static vip.qsos.im.lib.model.proto.SessionProto.Model parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static vip.qsos.im.lib.model.proto.SessionProto.Model parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static vip.qsos.im.lib.model.proto.SessionProto.Model parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static vip.qsos.im.lib.model.proto.SessionProto.Model parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static vip.qsos.im.lib.model.proto.SessionProto.Model parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static vip.qsos.im.lib.model.proto.SessionProto.Model parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static vip.qsos.im.lib.model.proto.SessionProto.Model parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static vip.qsos.im.lib.model.proto.SessionProto.Model parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static vip.qsos.im.lib.model.proto.SessionProto.Model parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static vip.qsos.im.lib.model.proto.SessionProto.Model parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static vip.qsos.im.lib.model.proto.SessionProto.Model parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static vip.qsos.im.lib.model.proto.SessionProto.Model parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(vip.qsos.im.lib.model.proto.SessionProto.Model prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     *消息会话包装类
     * </pre>
     *
     * Protobuf type {@code vip.qsos.im.lib.model.proto.Model}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          vip.qsos.im.lib.model.proto.SessionProto.Model, Builder> implements
        // @@protoc_insertion_point(builder_implements:vip.qsos.im.lib.model.proto.Model)
        vip.qsos.im.lib.model.proto.SessionProto.ModelOrBuilder {
      // Construct using vip.qsos.im.lib.model.proto.SessionProto.Model.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       *数据库主键ID
       * </pre>
       *
       * <code>int64 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public long getId() {
        return instance.getId();
      }
      /**
       * <pre>
       *数据库主键ID
       * </pre>
       *
       * <code>int64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {
        copyOnWrite();
        instance.setId(value);
        return this;
      }
      /**
       * <pre>
       *数据库主键ID
       * </pre>
       *
       * <code>int64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        copyOnWrite();
        instance.clearId();
        return this;
      }

      /**
       * <pre>
       *session绑定的用户账号
       * </pre>
       *
       * <code>string account = 2;</code>
       * @return The account.
       */
      @java.lang.Override
      public java.lang.String getAccount() {
        return instance.getAccount();
      }
      /**
       * <pre>
       *session绑定的用户账号
       * </pre>
       *
       * <code>string account = 2;</code>
       * @return The bytes for account.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getAccountBytes() {
        return instance.getAccountBytes();
      }
      /**
       * <pre>
       *session绑定的用户账号
       * </pre>
       *
       * <code>string account = 2;</code>
       * @param value The account to set.
       * @return This builder for chaining.
       */
      public Builder setAccount(
          java.lang.String value) {
        copyOnWrite();
        instance.setAccount(value);
        return this;
      }
      /**
       * <pre>
       *session绑定的用户账号
       * </pre>
       *
       * <code>string account = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAccount() {
        copyOnWrite();
        instance.clearAccount();
        return this;
      }
      /**
       * <pre>
       *session绑定的用户账号
       * </pre>
       *
       * <code>string account = 2;</code>
       * @param value The bytes for account to set.
       * @return This builder for chaining.
       */
      public Builder setAccountBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setAccountBytes(value);
        return this;
      }

      /**
       * <pre>
       *session在本台服务器上的ID
       * </pre>
       *
       * <code>string nid = 3;</code>
       * @return The nid.
       */
      @java.lang.Override
      public java.lang.String getNid() {
        return instance.getNid();
      }
      /**
       * <pre>
       *session在本台服务器上的ID
       * </pre>
       *
       * <code>string nid = 3;</code>
       * @return The bytes for nid.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getNidBytes() {
        return instance.getNidBytes();
      }
      /**
       * <pre>
       *session在本台服务器上的ID
       * </pre>
       *
       * <code>string nid = 3;</code>
       * @param value The nid to set.
       * @return This builder for chaining.
       */
      public Builder setNid(
          java.lang.String value) {
        copyOnWrite();
        instance.setNid(value);
        return this;
      }
      /**
       * <pre>
       *session在本台服务器上的ID
       * </pre>
       *
       * <code>string nid = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearNid() {
        copyOnWrite();
        instance.clearNid();
        return this;
      }
      /**
       * <pre>
       *session在本台服务器上的ID
       * </pre>
       *
       * <code>string nid = 3;</code>
       * @param value The bytes for nid to set.
       * @return This builder for chaining.
       */
      public Builder setNidBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setNidBytes(value);
        return this;
      }

      /**
       * <pre>
       *客户端 ID (设备号码+应用包名),ios为 device token 
       * </pre>
       *
       * <code>string deviceId = 4;</code>
       * @return The deviceId.
       */
      @java.lang.Override
      public java.lang.String getDeviceId() {
        return instance.getDeviceId();
      }
      /**
       * <pre>
       *客户端 ID (设备号码+应用包名),ios为 device token 
       * </pre>
       *
       * <code>string deviceId = 4;</code>
       * @return The bytes for deviceId.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getDeviceIdBytes() {
        return instance.getDeviceIdBytes();
      }
      /**
       * <pre>
       *客户端 ID (设备号码+应用包名),ios为 device token 
       * </pre>
       *
       * <code>string deviceId = 4;</code>
       * @param value The deviceId to set.
       * @return This builder for chaining.
       */
      public Builder setDeviceId(
          java.lang.String value) {
        copyOnWrite();
        instance.setDeviceId(value);
        return this;
      }
      /**
       * <pre>
       *客户端 ID (设备号码+应用包名),ios为 device token 
       * </pre>
       *
       * <code>string deviceId = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearDeviceId() {
        copyOnWrite();
        instance.clearDeviceId();
        return this;
      }
      /**
       * <pre>
       *客户端 ID (设备号码+应用包名),ios为 device token 
       * </pre>
       *
       * <code>string deviceId = 4;</code>
       * @param value The bytes for deviceId to set.
       * @return This builder for chaining.
       */
      public Builder setDeviceIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setDeviceIdBytes(value);
        return this;
      }

      /**
       * <pre>
       *session绑定的服务器IP
       * </pre>
       *
       * <code>string host = 5;</code>
       * @return The host.
       */
      @java.lang.Override
      public java.lang.String getHost() {
        return instance.getHost();
      }
      /**
       * <pre>
       *session绑定的服务器IP
       * </pre>
       *
       * <code>string host = 5;</code>
       * @return The bytes for host.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getHostBytes() {
        return instance.getHostBytes();
      }
      /**
       * <pre>
       *session绑定的服务器IP
       * </pre>
       *
       * <code>string host = 5;</code>
       * @param value The host to set.
       * @return This builder for chaining.
       */
      public Builder setHost(
          java.lang.String value) {
        copyOnWrite();
        instance.setHost(value);
        return this;
      }
      /**
       * <pre>
       *session绑定的服务器IP
       * </pre>
       *
       * <code>string host = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearHost() {
        copyOnWrite();
        instance.clearHost();
        return this;
      }
      /**
       * <pre>
       *session绑定的服务器IP
       * </pre>
       *
       * <code>string host = 5;</code>
       * @param value The bytes for host to set.
       * @return This builder for chaining.
       */
      public Builder setHostBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setHostBytes(value);
        return this;
      }

      /**
       * <pre>
       *客户端设备类型
       * </pre>
       *
       * <code>string channel = 6;</code>
       * @return The channel.
       */
      @java.lang.Override
      public java.lang.String getChannel() {
        return instance.getChannel();
      }
      /**
       * <pre>
       *客户端设备类型
       * </pre>
       *
       * <code>string channel = 6;</code>
       * @return The bytes for channel.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getChannelBytes() {
        return instance.getChannelBytes();
      }
      /**
       * <pre>
       *客户端设备类型
       * </pre>
       *
       * <code>string channel = 6;</code>
       * @param value The channel to set.
       * @return This builder for chaining.
       */
      public Builder setChannel(
          java.lang.String value) {
        copyOnWrite();
        instance.setChannel(value);
        return this;
      }
      /**
       * <pre>
       *客户端设备类型
       * </pre>
       *
       * <code>string channel = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearChannel() {
        copyOnWrite();
        instance.clearChannel();
        return this;
      }
      /**
       * <pre>
       *客户端设备类型
       * </pre>
       *
       * <code>string channel = 6;</code>
       * @param value The bytes for channel to set.
       * @return This builder for chaining.
       */
      public Builder setChannelBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setChannelBytes(value);
        return this;
      }

      /**
       * <pre>
       *客户端设备型号
       * </pre>
       *
       * <code>string deviceModel = 7;</code>
       * @return The deviceModel.
       */
      @java.lang.Override
      public java.lang.String getDeviceModel() {
        return instance.getDeviceModel();
      }
      /**
       * <pre>
       *客户端设备型号
       * </pre>
       *
       * <code>string deviceModel = 7;</code>
       * @return The bytes for deviceModel.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getDeviceModelBytes() {
        return instance.getDeviceModelBytes();
      }
      /**
       * <pre>
       *客户端设备型号
       * </pre>
       *
       * <code>string deviceModel = 7;</code>
       * @param value The deviceModel to set.
       * @return This builder for chaining.
       */
      public Builder setDeviceModel(
          java.lang.String value) {
        copyOnWrite();
        instance.setDeviceModel(value);
        return this;
      }
      /**
       * <pre>
       *客户端设备型号
       * </pre>
       *
       * <code>string deviceModel = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearDeviceModel() {
        copyOnWrite();
        instance.clearDeviceModel();
        return this;
      }
      /**
       * <pre>
       *客户端设备型号
       * </pre>
       *
       * <code>string deviceModel = 7;</code>
       * @param value The bytes for deviceModel to set.
       * @return This builder for chaining.
       */
      public Builder setDeviceModelBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setDeviceModelBytes(value);
        return this;
      }

      /**
       * <pre>
       *客户端应用版本
       * </pre>
       *
       * <code>string clientVersion = 8;</code>
       * @return The clientVersion.
       */
      @java.lang.Override
      public java.lang.String getClientVersion() {
        return instance.getClientVersion();
      }
      /**
       * <pre>
       *客户端应用版本
       * </pre>
       *
       * <code>string clientVersion = 8;</code>
       * @return The bytes for clientVersion.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getClientVersionBytes() {
        return instance.getClientVersionBytes();
      }
      /**
       * <pre>
       *客户端应用版本
       * </pre>
       *
       * <code>string clientVersion = 8;</code>
       * @param value The clientVersion to set.
       * @return This builder for chaining.
       */
      public Builder setClientVersion(
          java.lang.String value) {
        copyOnWrite();
        instance.setClientVersion(value);
        return this;
      }
      /**
       * <pre>
       *客户端应用版本
       * </pre>
       *
       * <code>string clientVersion = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearClientVersion() {
        copyOnWrite();
        instance.clearClientVersion();
        return this;
      }
      /**
       * <pre>
       *客户端应用版本
       * </pre>
       *
       * <code>string clientVersion = 8;</code>
       * @param value The bytes for clientVersion to set.
       * @return This builder for chaining.
       */
      public Builder setClientVersionBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setClientVersionBytes(value);
        return this;
      }

      /**
       * <pre>
       *客户端系统版本
       * </pre>
       *
       * <code>string systemVersion = 9;</code>
       * @return The systemVersion.
       */
      @java.lang.Override
      public java.lang.String getSystemVersion() {
        return instance.getSystemVersion();
      }
      /**
       * <pre>
       *客户端系统版本
       * </pre>
       *
       * <code>string systemVersion = 9;</code>
       * @return The bytes for systemVersion.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getSystemVersionBytes() {
        return instance.getSystemVersionBytes();
      }
      /**
       * <pre>
       *客户端系统版本
       * </pre>
       *
       * <code>string systemVersion = 9;</code>
       * @param value The systemVersion to set.
       * @return This builder for chaining.
       */
      public Builder setSystemVersion(
          java.lang.String value) {
        copyOnWrite();
        instance.setSystemVersion(value);
        return this;
      }
      /**
       * <pre>
       *客户端系统版本
       * </pre>
       *
       * <code>string systemVersion = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearSystemVersion() {
        copyOnWrite();
        instance.clearSystemVersion();
        return this;
      }
      /**
       * <pre>
       *客户端系统版本
       * </pre>
       *
       * <code>string systemVersion = 9;</code>
       * @param value The bytes for systemVersion to set.
       * @return This builder for chaining.
       */
      public Builder setSystemVersionBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSystemVersionBytes(value);
        return this;
      }

      /**
       * <pre>
       *客户端登录时间
       * </pre>
       *
       * <code>int64 bindTime = 10;</code>
       * @return The bindTime.
       */
      @java.lang.Override
      public long getBindTime() {
        return instance.getBindTime();
      }
      /**
       * <pre>
       *客户端登录时间
       * </pre>
       *
       * <code>int64 bindTime = 10;</code>
       * @param value The bindTime to set.
       * @return This builder for chaining.
       */
      public Builder setBindTime(long value) {
        copyOnWrite();
        instance.setBindTime(value);
        return this;
      }
      /**
       * <pre>
       *客户端登录时间
       * </pre>
       *
       * <code>int64 bindTime = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearBindTime() {
        copyOnWrite();
        instance.clearBindTime();
        return this;
      }

      /**
       * <pre>
       *客户端经度
       * </pre>
       *
       * <code>double longitude = 11;</code>
       * @return The longitude.
       */
      @java.lang.Override
      public double getLongitude() {
        return instance.getLongitude();
      }
      /**
       * <pre>
       *客户端经度
       * </pre>
       *
       * <code>double longitude = 11;</code>
       * @param value The longitude to set.
       * @return This builder for chaining.
       */
      public Builder setLongitude(double value) {
        copyOnWrite();
        instance.setLongitude(value);
        return this;
      }
      /**
       * <pre>
       *客户端经度
       * </pre>
       *
       * <code>double longitude = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearLongitude() {
        copyOnWrite();
        instance.clearLongitude();
        return this;
      }

      /**
       * <pre>
       *客户端维度
       * </pre>
       *
       * <code>double latitude = 12;</code>
       * @return The latitude.
       */
      @java.lang.Override
      public double getLatitude() {
        return instance.getLatitude();
      }
      /**
       * <pre>
       *客户端维度
       * </pre>
       *
       * <code>double latitude = 12;</code>
       * @param value The latitude to set.
       * @return This builder for chaining.
       */
      public Builder setLatitude(double value) {
        copyOnWrite();
        instance.setLatitude(value);
        return this;
      }
      /**
       * <pre>
       *客户端维度
       * </pre>
       *
       * <code>double latitude = 12;</code>
       * @return This builder for chaining.
       */
      public Builder clearLatitude() {
        copyOnWrite();
        instance.clearLatitude();
        return this;
      }

      /**
       * <pre>
       *客户端位置
       * </pre>
       *
       * <code>string location = 13;</code>
       * @return The location.
       */
      @java.lang.Override
      public java.lang.String getLocation() {
        return instance.getLocation();
      }
      /**
       * <pre>
       *客户端位置
       * </pre>
       *
       * <code>string location = 13;</code>
       * @return The bytes for location.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getLocationBytes() {
        return instance.getLocationBytes();
      }
      /**
       * <pre>
       *客户端位置
       * </pre>
       *
       * <code>string location = 13;</code>
       * @param value The location to set.
       * @return This builder for chaining.
       */
      public Builder setLocation(
          java.lang.String value) {
        copyOnWrite();
        instance.setLocation(value);
        return this;
      }
      /**
       * <pre>
       *客户端位置
       * </pre>
       *
       * <code>string location = 13;</code>
       * @return This builder for chaining.
       */
      public Builder clearLocation() {
        copyOnWrite();
        instance.clearLocation();
        return this;
      }
      /**
       * <pre>
       *客户端位置
       * </pre>
       *
       * <code>string location = 13;</code>
       * @param value The bytes for location to set.
       * @return This builder for chaining.
       */
      public Builder setLocationBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setLocationBytes(value);
        return this;
      }

      /**
       * <pre>
       *apns推送状态
       * </pre>
       *
       * <code>int32 apns = 14;</code>
       * @return The apns.
       */
      @java.lang.Override
      public int getApns() {
        return instance.getApns();
      }
      /**
       * <pre>
       *apns推送状态
       * </pre>
       *
       * <code>int32 apns = 14;</code>
       * @param value The apns to set.
       * @return This builder for chaining.
       */
      public Builder setApns(int value) {
        copyOnWrite();
        instance.setApns(value);
        return this;
      }
      /**
       * <pre>
       *apns推送状态
       * </pre>
       *
       * <code>int32 apns = 14;</code>
       * @return This builder for chaining.
       */
      public Builder clearApns() {
        copyOnWrite();
        instance.clearApns();
        return this;
      }

      /**
       * <pre>
       *客户端在线状态
       * </pre>
       *
       * <code>int32 state = 15;</code>
       * @return The state.
       */
      @java.lang.Override
      public int getState() {
        return instance.getState();
      }
      /**
       * <pre>
       *客户端在线状态
       * </pre>
       *
       * <code>int32 state = 15;</code>
       * @param value The state to set.
       * @return This builder for chaining.
       */
      public Builder setState(int value) {
        copyOnWrite();
        instance.setState(value);
        return this;
      }
      /**
       * <pre>
       *客户端在线状态
       * </pre>
       *
       * <code>int32 state = 15;</code>
       * @return This builder for chaining.
       */
      public Builder clearState() {
        copyOnWrite();
        instance.clearState();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:vip.qsos.im.lib.model.proto.Model)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new vip.qsos.im.lib.model.proto.SessionProto.Model();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "id_",
              "account_",
              "nid_",
              "deviceId_",
              "host_",
              "channel_",
              "deviceModel_",
              "clientVersion_",
              "systemVersion_",
              "bindTime_",
              "longitude_",
              "latitude_",
              "location_",
              "apns_",
              "state_",
            };
            java.lang.String info =
                "\u0000\u000f\u0000\u0000\u0001\u000f\u000f\u0000\u0000\u0000\u0001\u0002\u0002\u0208" +
                "\u0003\u0208\u0004\u0208\u0005\u0208\u0006\u0208\u0007\u0208\b\u0208\t\u0208\n\u0002" +
                "\u000b\u0000\f\u0000\r\u0208\u000e\u0004\u000f\u0004";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<vip.qsos.im.lib.model.proto.SessionProto.Model> parser = PARSER;
          if (parser == null) {
            synchronized (vip.qsos.im.lib.model.proto.SessionProto.Model.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<vip.qsos.im.lib.model.proto.SessionProto.Model>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:vip.qsos.im.lib.model.proto.Model)
    private static final vip.qsos.im.lib.model.proto.SessionProto.Model DEFAULT_INSTANCE;
    static {
      Model defaultInstance = new Model();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        Model.class, defaultInstance);
    }

    public static vip.qsos.im.lib.model.proto.SessionProto.Model getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Model> PARSER;

    public static com.google.protobuf.Parser<Model> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
